name: Own Demo Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Executing Multiline Shell Commands
        run: | 
             echo "First Line"
             echo "Second Line"
